

export const TICKET_IN_PROGRESS = "IN_PROGRESS";
export const TICKET_STATUS = "TICKET_STATUS";
export const ASSIGNED = "ASSIGNED";
export const PAYMENT_MODE = "PAYMENT_MODE";
export const REJECTED = "REJECTED";
export const APPROVED = "APPROVED";
export const TYPE_OF_ORG = "TYPE_OF_ORG";
export const CATEGORY_OF_ORG = "CATEGORY_OF_ORG";
export const SIZE_OF_ORG = "SIZE_OF_ORG";
export const CUSTOMER_LEAD_ACTIVE = "ACTIVE";
export const ESCALATED = "ESCALATED";
export const RAISED = "RAISED";
export const IN_PROGRESS = "IN_PROGRESS";
export const TICKET_CLOSED = "TICKET_CLOSED";
export const ASSET_UNIQUE_IDENTIFIER_TYPE = "ASSET_UNIQUE_IDENTIFIER_TYPE";
export const ASSET_LICENCED_TYPE = "ASSET_LICENCED_TYPE";
export const ASSET_IMPACT = "ASSET_IMPACT";
export const TICKET_ASSIGNED = "ASSIGNED";
export const TICKET_WORK_COMPLETED = "WORK_COMPLETED";
export const TICKET_PAID = "PAID";
export const TICKET_SERVICE_TYPE = "TICKET_SERVICE_TYPE";
export const OPENED = "OPENED";
export const TICKET_OPENED = "OPENED";
export const TICKET_CUSTOMER_NOT_AVAILABLE = "CUSTOMER_NOT_AVAILABLE"
export const TICKET_SPARE_REQUIRED = "SPARE_REQUIRED"
export const TICKET_CANNOT_RESOLVE = "CANNOT_RESOLVE"
export const RELATIONSHIP = "RELATIONSHIP"
export const NORMAL_FIELD = 'NORMAL_FIELD'
export const NORMAL_REMOTE = 'NORMAL_REMOTE'
export const EXPRESS_FIELD = 'EXPRESS_FIELD'
export const EXPRESS_REMOTE = 'EXPRESS_REMOTE'
export const FAMILY = 'FAMILY'
export const STAFF = 'STAFF'

